version: '3'

services:
  web:
    image: python:3.8
    working_dir: /app
    volumes:
      - ./app:/src
    ports:
      - "5050:5050"
    environment:
      - FLASK_APP=app.py
      - FLASK_RUN_HOST=0.0.0.0

    command: >
      sh -c "pip install flask flask_sqlalchemy flask-wtf && flask --app despysas run"

    depends_on:
      - db
    links:
      - db

  db:
    image: mtsribeiro/sqlite3-image:0.1
    volumes:
      - ./app:/src
    working_dir: ./app:/src

    command: sqlite3 ${pwd}/vendas.sqlite

  julia:
      image: julia:latest 
      volumes:
        - ./app:/src 
      working_dir: /src/faturamento
      command: julia -e 'using Pkg; Pkg.add("Stipple"); Pkg.add("StippleUI"); Pkg.add("StipplePlotly"); Pkg.add("SQLite"); Pkg.add("DataFrames"); julia app.jl'  
      depends_on:
        - db
      links:
        - db
  